stages:
    - syncStep
    - buildStep
 
syncStep_dev:
    stage: syncStep
    tags:
        - Big_Data_Midas_Hbase_Dev
    script:
        - echo Start of Sync Step - DEV
        - echo rsync -Ervz * /tmp/builds/TKed_koT/0/midas-hbase/ingestion/.git/
        - ls /tmp/builds/TKed_koT/0/midas-hbase/ingestion/.git/ 
        - rsync -Ervz * /tmp/builds/TKed_koT/0/midas-hbase/ingestion/.git/
        - ls /tmp/builds/TKed_koT/0/midas-hbase/ingestion/.git/
        - echo End of Sync Step - DEV
    ##This will ensure you are syncing code from branch named "DEV_BRANCH_NAME"
    ##only:
        ##- master
 
 
##Include ssh build step in your script, if you had ssh build step in your TeamCity job and/or have a need to run your job after syncing your code
buildStep_dev:
    stage: buildStep
    tags:
        - Big_Data_Midas_Hbase_Dev
    script:
        - export http_proxy="http://proxy-chain.intel.com:911"
        - export https_proxy="https://proxy-chain.intel.com:912"
        - echo Starting build step - DEV
        - echo sbt clean
        - sbt clean
        - echo bt compile package test:package
        - sbt compile package test:package
        - echo End of build step - DEV